export const siteConfig = {
  name: "GreenTheory",
  tagline: "Turf. Plants. Precision.",
  url: "https://greentheory.au",
  email: "hello@greentheory.au",
  phone: "0421573573",
  phoneDisplay: "0421 573 573",
  director: "Ash Jose",
  locale: "en_AU",
  areaServed: [
    "Adelaide",
    "Adelaide Eastern Suburbs",
    "Adelaide Inner Suburbs",
    "Burnside",
    "Norwood",
    "Unley",
    "Kensington",
    "Glen Osmond",
    "Beaumont",
    "Rose Park",
    "Toorak Gardens",
    "St Peters",
    "College Park",
    "Kent Town",
  ],
  services: [
    "Turf care",
    "Hedging",
    "Irrigation",
    "Lawn renovations",
    "Soft landscaping",
    "Garden maintenance",
  ],
} as const;

export const seo = {
  title: "Adelaide Gardener | Turf, Hedging & Garden Care | GreenTheory",
  titleTemplate: "%s | GreenTheory Adelaide",
  description:
    "GreenTheory is a professional Adelaide gardener offering turf care, hedging, irrigation, lawn renovations and soft landscaping across Adelaide's eastern and inner suburbs. Call Ash Jose on 0421 573 573.",
  keywords: [
    "Adelaide gardener",
    "gardener Adelaide",
    "Adelaide garden care",
    "turf care Adelaide",
    "hedging Adelaide",
    "lawn renovation Adelaide",
    "soft landscaping Adelaide",
    "irrigation Adelaide",
    "horticulturalist Adelaide",
    "landscaping Adelaide eastern suburbs",
    "garden maintenance Adelaide inner suburbs",
    "local gardener Adelaide",
    "GreenTheory",
    "Ash Jose gardener",
  ],
  ogImage: "/logo.png",
} as const;
